// <auto-generated />
using System;
using EV_StationRentalSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EV_StationRentalSystem.Insfrastructure.Migrations
{
    [DbContext(typeof(FleetDbContext))]
    [Migration("20251029053702_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.BranchDestination", b =>
                {
                    b.Property<Guid>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingHours")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BranchId");

                    b.ToTable("BranchDestinations");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.ChargingRecord", b =>
                {
                    b.Property<Guid>("ChargingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchDestinationBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChargedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("EnergyAdded")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChargingId");

                    b.HasIndex("BranchDestinationBranchId");

                    b.HasIndex("VehicleId");

                    b.ToTable("ChargingRecords");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.MaintenanceRecord", b =>
                {
                    b.Property<Guid>("MaintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerformedBy")
                        .HasColumnType("int");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MaintenanceId");

                    b.HasIndex("VehicleId");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.TypeVehicle", b =>
                {
                    b.Property<Guid>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DefaultBattery")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId");

                    b.ToTable("TypeVehicles");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BatteryCapacity")
                        .HasColumnType("float");

                    b.Property<string>("ChassisNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("int");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("QRCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VehicleId");

                    b.HasIndex("TypeId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.VehicleAvailabilityByBranch", b =>
                {
                    b.Property<Guid>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableCount")
                        .HasColumnType("int");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("InUseCount")
                        .HasColumnType("int");

                    b.Property<int>("MaintenanceCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("BranchId");

                    b.ToTable("VehicleAvailabilities");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.VehicleRelocation", b =>
                {
                    b.Property<Guid>("RelocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpectedArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RelocationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ToBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RelocationId");

                    b.HasIndex("ToBranchId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleRelocations");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.VehicleSchedule", b =>
                {
                    b.Property<Guid>("VehicleScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchDestinationBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VehicleScheduleId");

                    b.HasIndex("BranchDestinationBranchId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleSchedules");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.ChargingRecord", b =>
                {
                    b.HasOne("EV_StationRentalSystem.Core.Entities.BranchDestination", "BranchDestination")
                        .WithMany()
                        .HasForeignKey("BranchDestinationBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_StationRentalSystem.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("ChargingRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BranchDestination");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.MaintenanceRecord", b =>
                {
                    b.HasOne("EV_StationRentalSystem.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.Vehicle", b =>
                {
                    b.HasOne("EV_StationRentalSystem.Core.Entities.TypeVehicle", "TypeVehicle")
                        .WithMany("Vehicles")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TypeVehicle");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.VehicleAvailabilityByBranch", b =>
                {
                    b.HasOne("EV_StationRentalSystem.Core.Entities.BranchDestination", "BranchDestination")
                        .WithMany("VehicleAvailabilities")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BranchDestination");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.VehicleRelocation", b =>
                {
                    b.HasOne("EV_StationRentalSystem.Core.Entities.BranchDestination", "ToBranch")
                        .WithMany()
                        .HasForeignKey("ToBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_StationRentalSystem.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleRelocations")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ToBranch");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.VehicleSchedule", b =>
                {
                    b.HasOne("EV_StationRentalSystem.Core.Entities.BranchDestination", "BranchDestination")
                        .WithMany()
                        .HasForeignKey("BranchDestinationBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EV_StationRentalSystem.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleSchedules")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BranchDestination");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.BranchDestination", b =>
                {
                    b.Navigation("VehicleAvailabilities");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.TypeVehicle", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.Vehicle", b =>
                {
                    b.Navigation("ChargingRecords");

                    b.Navigation("MaintenanceRecords");

                    b.Navigation("VehicleRelocations");

                    b.Navigation("VehicleSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
