// <auto-generated />
using System;
using EV_StationRentalSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EV_StationRentalSystem.Infrastructure.Migrations
{
    [DbContext(typeof(RentalPaymentDbContext))]
    partial class RentalPaymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.Checkin", b =>
                {
                    b.Property<Guid>("CheckinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BatteryLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("OdometerReading")
                        .HasColumnType("int");

                    b.Property<Guid>("RentalOrderDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RentalOrderRentalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CheckinId");

                    b.HasIndex("RentalOrderDetailId");

                    b.HasIndex("RentalOrderRentalId");

                    b.ToTable("Checkins");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.Checkout", b =>
                {
                    b.Property<Guid>("CheckoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BatteryLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ExtraFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OdometerReading")
                        .HasColumnType("int");

                    b.Property<Guid>("RentalOrderDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RentalOrderRentalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CheckoutId");

                    b.HasIndex("RentalOrderDetailId");

                    b.HasIndex("RentalOrderRentalId");

                    b.ToTable("Checkouts");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.FeedbackRating", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RentalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("RentalId");

                    b.ToTable("FeedbackRatings");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RentalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("RentalId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.PenaltyRecord", b =>
                {
                    b.Property<Guid>("PenaltyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IssuedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PenaltyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RentalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PenaltyId");

                    b.HasIndex("RentalId");

                    b.ToTable("PenaltyRecords");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.PhotoProof", b =>
                {
                    b.Property<Guid>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CheckinId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CheckoutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RentalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RentalOrderRentalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PhotoId");

                    b.HasIndex("CheckinId");

                    b.HasIndex("CheckoutId");

                    b.HasIndex("RentalOrderRentalId");

                    b.ToTable("PhotoProofs");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.RentalContract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<string>("ContractFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RentalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SignedByRenter")
                        .HasColumnType("int");

                    b.Property<int>("SignedByStaff")
                        .HasColumnType("int");

                    b.HasKey("ContractId");

                    b.HasIndex("RentalId")
                        .IsUnique();

                    b.ToTable("RentalContracts");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.RentalOrder", b =>
                {
                    b.Property<Guid>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ActualCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BranchEndId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchStartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("RenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RentalId");

                    b.ToTable("RentalOrders");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.RentalOrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RentalOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RentalOrderId");

                    b.ToTable("RentalOrderDetail", (string)null);
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.Checkin", b =>
                {
                    b.HasOne("EV_StationRentalSystem.Core.Entities.RentalOrderDetail", "RentalOrderDetail")
                        .WithMany("Checkins")
                        .HasForeignKey("RentalOrderDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EV_StationRentalSystem.Core.Entities.RentalOrder", null)
                        .WithMany("Checkins")
                        .HasForeignKey("RentalOrderRentalId");

                    b.Navigation("RentalOrderDetail");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.Checkout", b =>
                {
                    b.HasOne("EV_StationRentalSystem.Core.Entities.RentalOrderDetail", "RentalOrderDetail")
                        .WithMany("Checkouts")
                        .HasForeignKey("RentalOrderDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EV_StationRentalSystem.Core.Entities.RentalOrder", null)
                        .WithMany("Checkouts")
                        .HasForeignKey("RentalOrderRentalId");

                    b.Navigation("RentalOrderDetail");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.FeedbackRating", b =>
                {
                    b.HasOne("EV_StationRentalSystem.Core.Entities.RentalOrder", "RentalOrder")
                        .WithMany("FeedbackRatings")
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentalOrder");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.Payment", b =>
                {
                    b.HasOne("EV_StationRentalSystem.Core.Entities.RentalOrder", "RentalOrder")
                        .WithMany("Payments")
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentalOrder");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.PenaltyRecord", b =>
                {
                    b.HasOne("EV_StationRentalSystem.Core.Entities.RentalOrder", "RentalOrder")
                        .WithMany("PenaltyRecords")
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentalOrder");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.PhotoProof", b =>
                {
                    b.HasOne("EV_StationRentalSystem.Core.Entities.Checkin", "Checkin")
                        .WithMany("PhotoProofs")
                        .HasForeignKey("CheckinId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EV_StationRentalSystem.Core.Entities.Checkout", "Checkout")
                        .WithMany("PhotoProofs")
                        .HasForeignKey("CheckoutId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EV_StationRentalSystem.Core.Entities.RentalOrder", "RentalOrder")
                        .WithMany()
                        .HasForeignKey("RentalOrderRentalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checkin");

                    b.Navigation("Checkout");

                    b.Navigation("RentalOrder");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.RentalContract", b =>
                {
                    b.HasOne("EV_StationRentalSystem.Core.Entities.RentalOrder", "RentalOrder")
                        .WithOne("RentalContract")
                        .HasForeignKey("EV_StationRentalSystem.Core.Entities.RentalContract", "RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentalOrder");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.RentalOrderDetail", b =>
                {
                    b.HasOne("EV_StationRentalSystem.Core.Entities.RentalOrder", "RentalOrder")
                        .WithMany("RentalOrderDetails")
                        .HasForeignKey("RentalOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentalOrder");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.Checkin", b =>
                {
                    b.Navigation("PhotoProofs");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.Checkout", b =>
                {
                    b.Navigation("PhotoProofs");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.RentalOrder", b =>
                {
                    b.Navigation("Checkins");

                    b.Navigation("Checkouts");

                    b.Navigation("FeedbackRatings");

                    b.Navigation("Payments");

                    b.Navigation("PenaltyRecords");

                    b.Navigation("RentalContract")
                        .IsRequired();

                    b.Navigation("RentalOrderDetails");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.RentalOrderDetail", b =>
                {
                    b.Navigation("Checkins");

                    b.Navigation("Checkouts");
                });
#pragma warning restore 612, 618
        }
    }
}
