// <auto-generated />
using System;
using EV_StationRentalSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EV_StationRentalSystem.Infrastructure.Migrations
{
    [DbContext(typeof(WorkforceDbContext))]
    [Migration("20251104072115_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.Shift", b =>
                {
                    b.Property<Guid>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("ShiftId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.StaffAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Task")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("WorkdayId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssignmentId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("WorkdayId");

                    b.ToTable("StaffAssignments");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.StaffReassignment", b =>
                {
                    b.Property<Guid>("ReassignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ToBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReassignId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("ShiftId");

                    b.ToTable("StaffReassignments");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.Workday", b =>
                {
                    b.Property<Guid>("WorkdayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WorkdayId");

                    b.ToTable("Workdays");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.StaffAssignment", b =>
                {
                    b.HasOne("EV_StationRentalSystem.Core.Entities.Shift", "Shift")
                        .WithMany("StaffAssignments")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EV_StationRentalSystem.Core.Entities.Workday", "Workday")
                        .WithMany("StaffAssignments")
                        .HasForeignKey("WorkdayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("Workday");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.StaffReassignment", b =>
                {
                    b.HasOne("EV_StationRentalSystem.Core.Entities.StaffAssignment", "StaffAssignment")
                        .WithMany("StaffReassignments")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EV_StationRentalSystem.Core.Entities.Shift", "Shift")
                        .WithMany("StaffReassignments")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("StaffAssignment");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.Shift", b =>
                {
                    b.Navigation("StaffAssignments");

                    b.Navigation("StaffReassignments");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.StaffAssignment", b =>
                {
                    b.Navigation("StaffReassignments");
                });

            modelBuilder.Entity("EV_StationRentalSystem.Core.Entities.Workday", b =>
                {
                    b.Navigation("StaffAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
