version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_userservice
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=12345aA@
      - MSSQL_PID=Express
    ports:
      - '1444:1433'
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - userservice_network

volumes:
  sqlserver_data:

networks:
  userservice_network:
    driver: bridge
